In [1]:
import pandas as pd

df=pd.read_csv('covid19.csv')
df.head()

D:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Confirmed,Deaths,Recovered,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,IsNumericControl_Conf,IsNumericControl_Death,IsNumericControl_Rec,Source_File,Date_added,Copy_of_Confirmed,Copy_of_Deaths,Copy_of_Recovered
0,19.0,0,0,35019.0,Guadalupe,New Mexico,US,2020-05-22 02:36:51,34.863193,-104.790669,19.0,NaN,1,1,1,C:\Users\user\Desktop\SQL SSIS Homework\TermPr...,2020-05-31 02:11:47.280000000,19,0,0.0
1,116.0,0,0,48187.0,Guadalupe,Texas,US,2020-05-22 02:36:51,29.581653,-97.947868,116.0,NaN,1,1,1,C:\Users\user\Desktop\SQL SSIS Homework\TermPr...,2020-05-31 02:11:47.280000000,116,0,0.0
2,29.0,0,0,39059.0,Guernsey,Ohio,US,2020-05-22 02:36:51,40.050265,-81.492489,29.0,NaN,1,1,1,C:\Users\user\Desktop\SQL SSIS Homework\TermPr...,2020-05-31 02:11:47.280000000,29,0,0.0
3,931.0,49,0,37081.0,Guilford,North Carolina,US,2020-05-22 02:36:51,36.079595,-79.788249,882.0,NaN,1,1,1,C:\Users\user\Desktop\SQL SSIS Homework\TermPr...,2020-05-31 02:11:47.280000000,931,49,0.0
4,1.0,0,0,12045.0,Gulf,Florida,US,2020-05-22 02:36:51,29.935430,-85.242710,1.0,NaN,1,1,1,C:\Users\user\Desktop\SQL SSIS Homework\TermPr...,2020-05-31 02:11:47.280000000,1,0,0.0

In [2]:
df=df.loc[:,['Country_Region','Province_State','Last_Update','Copy_of_Confirmed','Copy_of_Deaths','Copy_of_Recovered']]
df.head()

,Country_Region,Province_State,Last_Update,Copy_of_Confirmed,Copy_of_Deaths,Copy_of_Recovered
0,US,New Mexico,2020-05-22 02:36:51,19,0,0.0
1,US,Texas,2020-05-22 02:36:51,116,0,0.0
2,US,Ohio,2020-05-22 02:36:51,29,0,0.0
3,US,North Carolina,2020-05-22 02:36:51,931,49,0.0
4,US,Florida,2020-05-22 02:36:51,1,0,0.0

In [3]:
df['Last_Update']=pd.to_datetime(df['Last_Update']).dt.date
df.head()

,Country_Region,Province_State,Last_Update,Copy_of_Confirmed,Copy_of_Deaths,Copy_of_Recovered
0,US,New Mexico,2020-05-22,19,0,0.0
1,US,Texas,2020-05-22,116,0,0.0
2,US,Ohio,2020-05-22,29,0,0.0
3,US,North Carolina,2020-05-22,931,49,0.0
4,US,Florida,2020-05-22,1,0,0.0

In [4]:
df_world=df.groupby('Last_Update').agg({'Copy_of_Confirmed':['sum'],'Copy_of_Deaths':['sum'],'Copy_of_Recovered':['sum']})
df_world.reset_index(inplace=True)
df_world=df_world.sort_values('Last_Update')
df_world.head()

  Last_Update Copy_of_Confirmed Copy_of_Deaths Copy_of_Recovered
                            sum            sum               sum
0  2020-01-22               555             17              28.0
1  2020-01-23               653             18              30.0
2  2020-01-24               941             26              36.0
3  2020-01-25              1438             42              39.0
4  2020-01-26              2118             56              52.0

In [5]:
df_world['Copy_of_Recovered']=pd.to_numeric(df_world['Copy_of_Recovered'].iloc[:,0], downcast='integer')
def to_daily():
    df_world['Daily_Confirmed'] = df_world['Copy_of_Confirmed'].diff().fillna(df_world['Copy_of_Confirmed'])
    df_world['Daily_Deaths'] = df_world['Copy_of_Deaths'].diff().fillna(df_world['Copy_of_Deaths'])
    df_world['Daily_Recovered'] = df_world['Copy_of_Recovered'].diff().fillna(df_world['Copy_of_Recovered'])
to_daily()
df_world.iloc[:,:]

,Last_Update,Copy_of_Confirmed,Copy_of_Deaths,Copy_of_Recovered,Daily_Confirmed,Daily_Deaths,Daily_Recovered
,,sum,sum,sum,,,
0,2020-01-22,555,17,28,555.0,17.0,28.0
1,2020-01-23,653,18,30,98.0,1.0,2.0
2,2020-01-24,941,26,36,288.0,8.0,6.0
3,2020-01-25,1438,42,39,497.0,16.0,3.0
4,2020-01-26,2118,56,52,680.0,14.0,13.0
5,2020-01-27,2927,82,61,809.0,26.0,9.0
6,2020-01-28,5578,131,107,2651.0,49.0,46.0
7,2020-01-29,6165,133,126,587.0,2.0,19.0
8,2020-01-30,8235,171,143,2070.0,38.0,17.0
9,2020-01-31,10151,213,239,1916.0,42.0,96.0
10,2020-02-01,12136,259,288,1985.0,46.0,49.0
11,2020-02-02,16798,366,463,4662.0,107.0,175.0
12,2020-02-03,19794,425,617,2996.0,59.0,154.0
13,2020-02-04,23982,491,866,4188.0,66.0,249.0
14,2020-02-05,27560,563,1120,3578.0,72.0,254.0
15,2020-02-06,30798,633,1507,3238.0,70.0,387.0
16,2020-02-07,34458,723,2000,3660.0,90.0,493.0
17,2020-02-08,37064,805,2646,2606.0,82.0,646.0
18,2020-02-09,40237,905,3251,3173.0,100.0,605.0
19,2020-02-10,42696,1012,3905,2459.0,107.0,654.0
20,2020-02-11,44582,1112,4689,1886.0,100.0,784.0
21,2020-02-12,45377,1126,5188,795.0,14.0,499.0
22,2020-02-13,60139,1370,6302,14762.0,244.0,1114.0
23,2020-02-14,2,0,0,-60137.0,-1370.0,-6302.0
24,2020-02-15,68,2,32,66.0,2.0,32.0
25,2020-02-16,65,0,43,-3.0,-2.0,11.0
26,2020-02-17,73162,1867,12529,73097.0,1867.0,12486.0
27,2020-02-18,74966,2004,14279,1804.0,137.0,1750.0
28,2020-02-21,180,0,180,-74786.0,-2004.0,-14099.0
29,2020-02-23,551,0,551,371.0,0.0,371.0
...,...,...,...,...,...,...,...
95,2020-04-30,3193886,227638,963660,77488.0,10485.0,43924.0
96,2020-05-01,3256846,233388,1005681,62960.0,5750.0,42021.0
97,2020-05-02,3343777,238650,1044204,86931.0,5262.0,38523.0
98,2020-05-03,3427343,243808,1083929,83566.0,5158.0,39725.0
99,2020-05-04,3506729,247470,1116019,79386.0,3662.0,32090.0
100,2020-05-05,3583055,251537,1153441,76326.0,4067.0,37422.0
101,2020-05-06,3662691,257239,1189499,79636.0,5702.0,36058.0
102,2020-05-07,3755341,263831,1235994,92650.0,6592.0,46495.0
103,2020-05-08,3845718,269567,1275257,90377.0,5736.0,39263.0
104,2020-05-09,3938064,274898,1312482,92346.0,5331.0,37225.0
105,2020-05-10,4024009,279311,1366014,85945.0,4413.0,53532.0
106,2020-05-11,4101699,282709,1399348,77690.0,3398.0,33334.0
107,2020-05-12,4177504,286330,1446539,75805.0,3621.0,47191.0
108,2020-05-13,4261955,291964,1483719,84451.0,5634.0,37180.0
109,2020-05-14,4347018,297197,1538779,85063.0,5233.0,55060.0
110,2020-05-15,4442163,302418,1578066,95145.0,5221.0,39287.0
111,2020-05-16,4542347,307666,1627210,100184.0,5248.0,49144.0
112,2020-05-17,4634068,311781,1683303,91721.0,4115.0,56093.0
113,2020-05-18,4713620,315185,1724053,79552.0,3404.0,40750.0
114,2020-05-19,4801943,318481,1776931,88323.0,3296.0,52878.0
115,2020-05-20,4897492,323285,1828923,95549.0,4804.0,51992.0
116,2020-05-21,4996472,328115,1887325,98980.0,4830.0,58402.0
117,2020-05-22,5102424,332924,1938571,105952.0,4809.0,51246.0
118,2020-05-23,5210817,338160,2046443,108393.0,5236.0,107872.0
119,2020-05-24,5310362,342097,2101966,99545.0,3937.0,55523.0
120,2020-05-25,5407613,345059,2158331,97251.0,2962.0,56365.0
121,2020-05-26,5495061,346232,2221457,87448.0,1173.0,63126.0
122,2020-05-27,5589626,350453,2276655,94565.0,4221.0,55198.0
123,2020-05-28,5691790,355629,2339742,102164.0,5176.0,63087.0
124,2020-05-29,5808946,360308,2405591,117156.0,4679.0,65849.0

In [6]:
def df_world_drop(arr):
    df_world.drop(arr,axis=0,inplace=True)
    df_world.reset_index(inplace=True,drop=True)
drop_indexes = [23,24,25,28,29,30,31,32,33,34,46,47,48,57,58,59,60,61,62,63,64,65,66,67,68,88,41,42,43,44,45,56]
df_world_drop(drop_indexes)
df_world.iloc[30:,:]

,Last_Update,Copy_of_Confirmed,Copy_of_Deaths,Copy_of_Recovered,Daily_Confirmed,Daily_Deaths,Daily_Recovered
,,sum,sum,sum,,,
30,2020-03-06,105998,3473,57666,8757.0,134.0,3543.0
31,2020-03-15,133342,4485,73746,-60614.0,-3328.0,-18865.0
32,2020-03-16,169719,7039,74861,36377.0,2554.0,1115.0
33,2020-03-17,182888,7762,74035,13169.0,723.0,-826.0
34,2020-03-18,202608,8646,77383,19720.0,884.0,3348.0
35,2020-03-19,225976,9703,76133,23368.0,1057.0,-1250.0
36,2020-03-20,257815,11163,80698,31839.0,1460.0,4565.0
37,2020-03-21,287778,12785,82764,29963.0,1622.0,2066.0
38,2020-04-04,1191067,64555,233589,1190047.0,64549.0,232637.0
39,2020-04-05,1268898,69316,250340,77831.0,4761.0,16751.0
40,2020-04-06,1346759,74647,271571,77861.0,5331.0,21231.0
41,2020-04-07,1421230,81825,288547,74471.0,7178.0,16976.0
42,2020-04-08,1504171,88274,314931,82941.0,6449.0,26384.0
43,2020-04-09,1606588,95525,358193,102417.0,7251.0,43262.0
44,2020-04-10,1699900,102468,377346,93312.0,6943.0,19153.0
45,2020-04-11,1768115,108465,391459,68215.0,5997.0,14113.0
46,2020-04-12,1842158,114060,409869,74043.0,5595.0,18410.0
47,2020-04-13,1911054,119420,434939,68896.0,5360.0,25070.0
48,2020-04-14,1987803,126242,478257,76749.0,6822.0,43318.0
49,2020-04-15,2053241,134129,500534,65438.0,7887.0,22277.0
50,2020-04-16,2147060,143764,528634,93819.0,9635.0,28100.0
51,2020-04-17,2239689,153804,559868,92629.0,10040.0,31234.0
52,2020-04-18,2320572,159489,587392,80883.0,5685.0,27524.0
53,2020-04-19,2396784,165006,611439,76212.0,5517.0,24047.0
54,2020-04-20,2465937,169951,631347,69153.0,4945.0,19908.0
55,2020-04-21,2541573,176507,664029,75636.0,6556.0,32682.0
56,2020-04-22,2735713,187593,695752,194140.0,11086.0,31723.0
57,2020-04-24,2723673,191158,735339,2587865.0,185669.0,734012.0
58,2020-04-25,2815899,197376,780987,92226.0,6218.0,45648.0
59,2020-04-26,2892398,203056,799151,76499.0,5680.0,18164.0
...,...,...,...,...,...,...,...
63,2020-04-30,3193886,227638,963660,77488.0,10485.0,43924.0
64,2020-05-01,3256846,233388,1005681,62960.0,5750.0,42021.0
65,2020-05-02,3343777,238650,1044204,86931.0,5262.0,38523.0
66,2020-05-03,3427343,243808,1083929,83566.0,5158.0,39725.0
67,2020-05-04,3506729,247470,1116019,79386.0,3662.0,32090.0
68,2020-05-05,3583055,251537,1153441,76326.0,4067.0,37422.0
69,2020-05-06,3662691,257239,1189499,79636.0,5702.0,36058.0
70,2020-05-07,3755341,263831,1235994,92650.0,6592.0,46495.0
71,2020-05-08,3845718,269567,1275257,90377.0,5736.0,39263.0
72,2020-05-09,3938064,274898,1312482,92346.0,5331.0,37225.0
73,2020-05-10,4024009,279311,1366014,85945.0,4413.0,53532.0
74,2020-05-11,4101699,282709,1399348,77690.0,3398.0,33334.0
75,2020-05-12,4177504,286330,1446539,75805.0,3621.0,47191.0
76,2020-05-13,4261955,291964,1483719,84451.0,5634.0,37180.0
77,2020-05-14,4347018,297197,1538779,85063.0,5233.0,55060.0
78,2020-05-15,4442163,302418,1578066,95145.0,5221.0,39287.0
79,2020-05-16,4542347,307666,1627210,100184.0,5248.0,49144.0
80,2020-05-17,4634068,311781,1683303,91721.0,4115.0,56093.0
81,2020-05-18,4713620,315185,1724053,79552.0,3404.0,40750.0
82,2020-05-19,4801943,318481,1776931,88323.0,3296.0,52878.0
83,2020-05-20,4897492,323285,1828923,95549.0,4804.0,51992.0
84,2020-05-21,4996472,328115,1887325,98980.0,4830.0,58402.0
85,2020-05-22,5102424,332924,1938571,105952.0,4809.0,51246.0
86,2020-05-23,5210817,338160,2046443,108393.0,5236.0,107872.0
87,2020-05-24,5310362,342097,2101966,99545.0,3937.0,55523.0
88,2020-05-25,5407613,345059,2158331,97251.0,2962.0,56365.0
89,2020-05-26,5495061,346232,2221457,87448.0,1173.0,63126.0
90,2020-05-27,5589626,350453,2276655,94565.0,4221.0,55198.0
91,2020-05-28,5691790,355629,2339742,102164.0,5176.0,63087.0
92,2020-05-29,5808946,360308,2405591,117156.0,4679.0,65849.0

In [7]:
"""
def clear_df_world():
    rows_to_clean = []
    while True:
        k=0
        for i in range(1,len(df_world)):
            if df_world.iloc[i,1] < df_world.iloc[i-1,1]:
                rows_to_clean.append(i)
                k+=1
        df_world.drop(rows_to_clean,axis=0,inplace=True)
        df_world.reset_index(inplace=True,drop=True)
        print(df_world.head(30))
        if k==0:
            break
clear_df_world()
"""

'\ndef clear_df_world():\n    rows_to_clean = []\n    while True:\n        k=0\n        for i in range(1,len(df_world)):\n            if df_world.iloc[i,1] < df_world.iloc[i-1,1]:\n                rows_to_clean.append(i)\n                k+=1\n        df_world.drop(rows_to_clean,axis=0,inplace=True)\n        df_world.reset_index(inplace=True,drop=True)\n        print(df_world.head(30))\n        if k==0:\n            break\nclear_df_world()\n'

In [8]:
#df_world.to_csv('df_world.csv', index=False)

In [9]:
df=df.iloc[:,df.columns != 'Province_State']
df_rdy = df.groupby(['Country_Region','Last_Update']).agg({'Copy_of_Confirmed':['sum'],'Copy_of_Deaths':['sum'],'Copy_of_Recovered':['sum']})
df_rdy.to_csv('df_rdy.csv')

                                           Copy_of_Confirmed Copy_of_Deaths  \
                                                         sum            sum
Country_Region                 Last_Update
Afghanistan                    2020-02-24                  7              0
                               2020-03-08                  8              0
                               2020-03-10                  5              0
                               2020-03-11                 21              0
                               2020-03-14                 11              0
                               2020-03-15                 16              0
                               2020-03-16                 21              0
                               2020-03-17                 66              0
                               2020-03-20                 48              0
                               2020-03-22                 40              1
                               2020-03-28                110              4
                               2020-03-29                120              4
                               2020-03-30                170              4
                               2020-04-02                273              6
                               2020-04-04                299              7
                               2020-04-05                349              7
                               2020-04-06                367             11
                               2020-04-07                423             14
                               2020-04-08                444             14
                               2020-04-09                484             15
                               2020-04-10                521             15
                               2020-04-11                555             18
                               2020-04-12                607             18
                               2020-04-13                665             21
                               2020-04-14                714             23
                               2020-04-15                784             25
                               2020-04-16                840             30
                               2020-04-17                906             30
                               2020-04-18                933             30
                               2020-04-19                996             33
...                                                      ...            ...
Zimbabwe                       2020-05-02                 40              4
                               2020-05-03                 34              4
                               2020-05-04                 34              4
                               2020-05-05                 34              4
                               2020-05-06                 34              4
                               2020-05-07                 34              4
                               2020-05-08                 34              4
                               2020-05-09                 34              4
                               2020-05-10                 35              4
                               2020-05-11                 36              4
                               2020-05-12                 36              4
                               2020-05-13                 36              4
                               2020-05-14                 37              4
                               2020-05-15                 37              4
                               2020-05-16                 42              4
                               2020-05-17                 42              4
                               2020-05-18                 44              4
                               2020-05-19                 46              4
                               2020-05-20                 46              4
                               2020-05-21                 48              4
                               2020-05-22                 51              4
                               2020-05-23                 51              4
                               2020-05-24                 56              4
                               2020-05-25                 56              4
                               2020-05-26                 56              4
                               2020-05-27                 56              4
                               2020-05-28                132              4
                               2020-05-29                149              4
occupied Palestinian territory 2020-03-10                 25              0
                               2020-03-11                  0              0

                                           Copy_of_Recovered
                                                         sum
Country_Region                 Last_Update
Afghanistan                    2020-02-24                0.0
                               2020-03-08                0.0
                               2020-03-10                0.0
                               2020-03-11                0.0
                               2020-03-14                0.0
                               2020-03-15                0.0
                               2020-03-16                1.0
                               2020-03-17                3.0
                               2020-03-20                2.0
                               2020-03-22                1.0
                               2020-03-28                2.0
                               2020-03-29                2.0
                               2020-03-30                2.0
                               2020-04-02               10.0
                               2020-04-04               10.0
                               2020-04-05               15.0
                               2020-04-06               18.0
                               2020-04-07               18.0
                               2020-04-08               29.0
                               2020-04-09               32.0
                               2020-04-10               32.0
                               2020-04-11               32.0
                               2020-04-12               32.0
                               2020-04-13               32.0
                               2020-04-14               40.0
                               2020-04-15               43.0
                               2020-04-16               54.0
                               2020-04-17               99.0
                               2020-04-18              112.0
                               2020-04-19              131.0
...                                                      ...
Zimbabwe                       2020-05-02                5.0
                               2020-05-03                5.0
                               2020-05-04                5.0
                               2020-05-05                5.0
                               2020-05-06                5.0
                               2020-05-07                5.0
                               2020-05-08                5.0
                               2020-05-09                9.0
                               2020-05-10                9.0
                               2020-05-11                9.0
                               2020-05-12                9.0
                               2020-05-13                9.0
                               2020-05-14               12.0
                               2020-05-15               13.0
                               2020-05-16               13.0
                               2020-05-17               13.0
                               2020-05-18               17.0
                               2020-05-19               18.0
                               2020-05-20               18.0
                               2020-05-21               18.0
                               2020-05-22               18.0
                               2020-05-23               18.0
                               2020-05-24               18.0
                               2020-05-25               25.0
                               2020-05-26               25.0
                               2020-05-27               25.0
                               2020-05-28               25.0
                               2020-05-29               28.0
occupied Palestinian territory 2020-03-10                0.0
                               2020-03-11                0.0

[13189 rows x 3 columns]